### ISSUE TITLE
Aligning stopped working after update

### ISSUE THREAD

**Issue by Andkoo** [adrianlee44/atom-aligner-scss#2]
After `2017-05-17 v1.2.0` update I am not able to align my SCSS in Vue component. My SCSS is closed in `<style lang="scss"></style>` tag. Before update everything was working except I couldn't align with `ctrl+alt+/`, but it was working with `ctrl+alt+shift+ú` on slovak keyboard so I got used to it. Now it isn't working at all.

**Comment by adrianlee44** [comment]
What character are you trying to align?

**Comment by Andkoo** [comment]
```
@include media(small) {
  width: 50%;
  margin-right: 8px;
  margin-bottom: 8px;
  margin-left: 8px;
}
```

**Comment by adrianlee44** [comment]
Can you check the `:` is enabled in `aligner-scss` settings?

**Comment by Andkoo** [comment]
![image](https://cloud.githubusercontent.com/assets/17043364/26096919/1104c0ca-3a23-11e7-9c96-f3eccf6731ec.png)

**Comment by adrianlee44** [comment]
Just published a patch and should fix the issue you are seeing. Thanks.

**Comment by Andkoo** [comment]
I have downloaded the `1.2.1` update, restarted Atom (twice just to be sure), unchecked `Enable aligning :`, checked it again. The problem still exists.

**Comment by adrianlee44** [comment]
Is this scss code block in a html `style` tag without any additional language package? 

Force downgrade aligner back to v0.22.3 should work for now as I continue to investigate this issue.

**Comment by Andkoo** [comment]
I am using `vue-cli`, running my project on `webpack`, I am loading SCSS with `sass-loader 6.0.3` and writing it in between `<style lang="scss">` and `</style>` in every Vue component. My SCSS is **NOT** scoped if that information helps too. Do you need any additional info?

**Comment by adrianlee44** [comment]
Thanks for the information. I believe I have found the issue and will be updating both aligner and this package.

**Comment by adrianlee44** [comment]
Updating aligner to v1.1.0 and aligner-scss to v1.3.0 should fix the issue.
